# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://biomed-laysumm.github.io'
baseurl: ''
title: ''
description: 'Host site for the 2023 shared task on the lay summarization of biomedical research articles.'
permalink: pretty
logo: "https://drive.google.com/uc?export=view&id=1RNAKAll8lK6F67neSdVXUBkrjeHJfk36"
# https://drive.google.com/file/d/1RNAKAll8lK6F67neSdVXUBkrjeHJfk36/view?usp=sharing
# https://drive.google.com/file/d/1Or9DjqdJM0gSNVXCywBaOR4M3V-okRzZ/view?usp=sharing
# https://drive.google.com/file/d/1fLludRWb2jERLxGotLp6Wk-VAJ1fBhAR/view?usp=share_link
#https://drive.google.com/file/d/1yN3u429vW5w9Ch1n7hjEDpGjzcrGNXwf/view?usp=sharing
css_inline: false

# Pagination
paginate: 5
paginate_path: blog/page:num


# Header nav
navigation_header:
- title: Home
  url: /#intro
- title: Important dates
  url: /#dates
- title: Tasks
  url: /#task
- title: Datasets
  url: /#data
- title: Evaluation
  url: /#eval
- title: Organizers
  url: /#us

custom_fonts:
  preconnect:
    - https://fonts.gstatic.com
  urls:
    - https://fonts.googleapis.com/css2?family=Rosario:wght@400;700&display=swap

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

